name: CI

on: 
  push:
  schedule:
    - cron: '30 3 12 * *'

jobs:
  test_links_utils:
    name: Check links in ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: setup python
      id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.16'

    - name: setup environment
      id: setup_env
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-xdist requests jupyter lxml numpy matplotlib scipy sympy

    - name: check links
      id: links
      run: python -m pytest -n auto ./tests/test_check_links_in_ipynb.py ./utils/tests/

  badges:
    name: Add Google Colab Badges
    needs: test_links_utils
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: setup environment
      id: setup
      run: python -m pip install bs4 jupyter lxml

    - name: Add/Update badges
      id: badges
      run: python ./utils/add_colab_main_buttons.py

    - name: Commit & push
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message : Add Github badges or remove ipynb `id`s

  test_ipynb:
    needs: badges
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        anaconda: [2020.07, 2021.04, nightly]
      fail-fast: false
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      env:
        CONDA_PYTHON: ${{ matrix.anaconda }}
      run: bash ./.github/workflows/build_env.sh
    - name: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/run_test.sh
